CREATE TABLE IF NOT EXISTS `personnel` (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `im` VARCHAR(20) NOT NULL UNIQUE COMMENT 'Indice Matricule unique',
    `matricule` VARCHAR(50) NULL COMMENT 'Matricule / Numéro d''identification',
    `lastname` VARCHAR(100) NOT NULL,
    `firstname` VARCHAR(100) NOT NULL,
    `grade` VARCHAR(100) NOT NULL COMMENT 'Grade / Rank',
    `fonction` VARCHAR(200) NOT NULL COMMENT 'Fonction / Position',
    `service` VARCHAR(200) NULL COMMENT 'Service d\'affectation',
    `date_prise_service` DATE NULL COMMENT 'Date de prise de service',
    `email` VARCHAR(255) NULL,
    `phone` VARCHAR(50) NULL,
    `adresse` TEXT NULL COMMENT 'Adresse personnelle',
    `date_naissance` DATE NULL COMMENT 'Date de naissance',
    `lieu_naissance` VARCHAR(255) NULL COMMENT 'Lieu de naissance',
    `cin` VARCHAR(50) NULL COMMENT 'Numéro national d\'identité (CIN)',
    `photo` VARCHAR(255) NULL COMMENT 'Photo filename',
    `status` ENUM('active', 'inactive') NOT NULL DEFAULT 'active',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_personnel_status` (`status`),
    INDEX `idx_personnel_grade` (`grade`),
    INDEX `idx_personnel_service` (`service`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
