CREATE TABLE IF NOT EXISTS mouvement_personnel (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    personnel_id INT UNSIGNED NOT NULL,
    im VARCHAR(20) NOT NULL,
    matricule VARCHAR(50) DEFAULT NULL,
    grade VARCHAR(100) DEFAULT NULL,
    fonction VARCHAR(200) DEFAULT NULL,
    service VARCHAR(200) DEFAULT NULL,
    nom VARCHAR(100) DEFAULT NULL,
    prenoms VARCHAR(100) DEFAULT NULL,
    type_mouvement VARCHAR(100) NOT NULL,
    date_depart DATE DEFAULT NULL,
    days INT UNSIGNED DEFAULT NULL,
    date_retour DATE DEFAULT NULL,
    retour ENUM('Oui','Non') NOT NULL DEFAULT 'Non',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (personnel_id) REFERENCES personnel(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
