CREATE TABLE IF NOT EXISTS comportement_personnel (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    personnel_id INT UNSIGNED NOT NULL,
    im VARCHAR(20) NOT NULL,
    grade VARCHAR(100) DEFAULT NULL,
    service VARCHAR(200) DEFAULT NULL,
    nom VARCHAR(100) DEFAULT NULL,
    prenoms VARCHAR(100) DEFAULT NULL,
    type ENUM('Positive','Negative') NOT NULL,
    date_comportement DATE NOT NULL,
    motif TEXT NOT NULL,
    decision TEXT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (personnel_id) REFERENCES personnel(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
