-- Requisition (Police Judiciaire — judicial requisitions).
-- Tracks requisitions issued to external services (TPH, médecin légiste,
-- CIM, etc.) with an official numero generated by PlainteSequence (REQ).

CREATE TABLE IF NOT EXISTS `requisition` (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `type` ENUM('TPH','MEDECIN_LEGISTE','CIM','AUTRE') NOT NULL COMMENT 'Type de réquisition',
    `date_requisition` DATE NOT NULL COMMENT 'Date de la réquisition',
    `numero` VARCHAR(100) NOT NULL COMMENT 'Numéro officiel (auto-généré ou saisi)',
    `numero_ttr` VARCHAR(100) NULL COMMENT 'N° TTR',
    `nom_substitut` VARCHAR(255) NULL COMMENT 'Nom du Substitut',
    `affaire` VARCHAR(255) NOT NULL COMMENT 'Affaire concernée',
    `numero_dossier` VARCHAR(100) NULL COMMENT 'Numéro du dossier concerné',
    `opj` VARCHAR(255) NULL COMMENT 'OPJ en charge',
    `created_by` INT UNSIGNED NULL COMMENT 'Agent who recorded the requisition',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT `fk_req_created_by` FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON DELETE SET NULL,
    UNIQUE KEY `uq_req_numero` (`numero`),
    INDEX `idx_req_type` (`type`),
    INDEX `idx_req_date` (`date_requisition`),
    INDEX `idx_req_affaire` (`affaire`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `attach_requisition` (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `requisition_id` INT UNSIGNED NOT NULL COMMENT 'FK to requisition',
    `title` VARCHAR(255) NOT NULL COMMENT 'Attachment title / description',
    `filename` VARCHAR(255) NOT NULL COMMENT 'Stored filename on disk',
    `original_filename` VARCHAR(255) NOT NULL COMMENT 'Original upload filename',
    `mime_type` VARCHAR(100) NULL COMMENT 'File MIME type',
    `file_size` INT UNSIGNED NULL COMMENT 'File size in bytes',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT `fk_attach_requisition` FOREIGN KEY (`requisition_id`) REFERENCES `requisition`(`id`) ON DELETE CASCADE,
    INDEX `idx_attach_requisition_id` (`requisition_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
